function doWork(num){
    var p= new Promise((resolve,reject)=>{
        setTimeout(()=>{
            if(num>10){
                reject('cant compute cube greater than 10');
            }
            resolve(num**3);
        },5000)
    });
    return p;
}
undefined
var p1= doWork(3);

undefined
p1
Promise {<pending>}[[Prototype]]: Promise[[PromiseState]]: "fulfilled"[[PromiseResult]]: 27
var p1= doWork(3);
p1.then(data=>console.log(data)).catch(err=>console.log(err));

Promise {<pending>}
VM664:2 27
var p1= doWork(100);
p1.then(data=>console.log(data)).catch(err=>console.log(err));

Promise {<pending>}
VM678:2 cant compute cube greater than 10
var p1= doWork(100);
p1.then(data=>console.log(data));

Promise {<pending>}
about:blank:1 Uncaught (in promise) cant compute cube greater than 10
Promise.then
(anonymous) @ VM683:2
